
server:
  port: ${PORT}

spring:
  config:
    import: env.properties
  application:
    name: server
  datasource:
    dbcp2:
      driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework: debug
